---
title: "Fibrosis_individual_analysis"
author: "Eren Kumak"
date: "2026-05-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

http://varianceexplained.org/statistics/interpreting-pvalue-histogram/
https://cran.r-project.org/web/packages/metaRNASeq/vignettes/metaRNASeq.pdf

```{r setup, include=FALSE}
library(data.table)
library(org.Hs.eg.db)
library(GEOquery)
library(Rtsne)
library(ggfortify)
library(dplyr)
library(gridExtra)
library(sva)
library(limma)
library(DESeq2)
library(edgeR)
library(plotly)
library(rmarkdown)
library(vegan)
library(tidyr)
library(pheatmap)
library(rococo)
library(parallel)
library(pbapply)
library(kohonen)
library(writexl)
library(phenopath)
library(metaRNASeq)
library(transport)
set.seed(42)
```

```{r}
load_dataset <- function(id){
  a <- fread(paste(id, ".tsv", sep="")) #load the count optained from NCBI-generated RNA-seq
  gene_names <- mapIds(
    org.Hs.eg.db,
    keys = as.character(a$GeneID),
    column = "SYMBOL", 
    keytype = "ENTREZID",
    multiVals = "first"
  ) # Get the gene symbols from ENTREZIDs
  a$GeneID <- gene_names #assign gene names instead of ENTREZID
  colnames(a)[1] <- "Gene" #change the column name
  a <- a[!duplicated(a$Gene),] #remove duplicated gene names
  a <- a[!is.na(a$Gene),] #remove any NAs in gene name
  a <- as.data.frame(a) #turn to df
  rownames(a) <- a$Gene #assign gene names as row names.
  a$Gene <- NULL #remove column
  return(a) #return fully modified df
}

load_meta <- function(id){
  a  <- getGEO(id, GSEMatrix = TRUE) #get the meta data via accession.
  a  <- pData(a[[1]]) #get the df portion
  return(a) #return it
}

individual_DESeq2 <- function(data,meta,col_index,name){
  meta <- meta[rownames(meta) %in% colnames(data),] #only get the samples where count data is availasble
  colData <- as.data.frame(meta[,col_index]) # create the design df
  rownames(colData) <- rownames(meta) 
  print(sum(rownames(colData) != colnames(data))) # check whether rownames of colData is same with colnames of data !should return 0
  colnames(colData) <- "stage" #name NAS as score
  colData <- colData %>% mutate(
    stage = case_when(
      stage %in% c(0,1,"0","1") ~ "F0_F1",
      stage %in% c(2,"2") ~ "F2",
      stage %in% c(3,"3") ~ "F3",
      stage %in% c(4,"4") ~ "F4",
      TRUE ~ "NA"
    ))
  colData <- colData[!colData[, 1] == "NA", , drop = FALSE]
  data <- data[,colnames(data) %in% rownames(colData)]
  colData$stage <- as.factor(colData$stage) #factorize them
  dds <- DESeqDataSetFromMatrix(countData = data, colData = colData, design = ~ stage) #classic DESeq2s
  dds <- DESeq(dds) 
  group_sizes <- table(colData$stage) #Counts how many samples are in each score group.
  smallest_group_size <- min(group_sizes) #Stores the size of the smallest group 
  keep <- rowSums(counts(dds) >= 10) >= smallest_group_size #Keeps genes that are expressed (b	%10 reads) in at least as many samples as the smallest group size. Example: If smallest group has 3 samples, this line keeps genes that are expressed in b	%3 samples.
  dds <- dds[keep,] #Applies that filter to the dataset.
  comb <- as.data.frame(t(combn(c("F0_F1","F2","F3","F4"), 2)))
  colnames(comb) <- c("A", "B")
  for (i in 1:nrow(comb)) {
    if (comb$B[i] %in% colData(dds)$stage) {
      res <- data.frame(DESeq2::results(dds, contrast = c("stage", comb$B[i], comb$A[i]), cooksCutoff = FALSE))
      
      if (!dir.exists(name)) {
        dir.create(name)
      }
      
      write.csv(res, paste0(name, "/fibrosis_DESEQ2_", as.character(comb$B[i]), "_VS_", as.character(comb$A[i]), ".csv"))
    } else {
      message(paste("Skipping", as.character(comb$B[i]), "- no samples found in data"))
    }
  } 
}
```

```{r}
GSE <- c("GSE174478", "GSE193066", "GSE130970", "GSE192959", "GSE162694", "GSE225740", "GSE185051", "GSE135251")
fibrosis_index <- c(42,45,45,41,44,37,44,43)

for(i in 1:length(GSE)){
  data <- load_dataset(GSE[i])
  meta <- load_meta(GSE[i])
  individual_DESeq2(data,meta,fibrosis_index[i],GSE[i])
}
```

```{r}
for (c in 1:6){
  studies <- list()  
  comb <- as.data.frame(t(combn(c("F0_F1","F2","F3","F4"), 2)))
  colnames(comb) <- c("A", "B")
  
  if(comb$B[c] == "F4"){
    GSE <- c("GSE174478", "GSE193066", "GSE130970", "GSE192959", "GSE162694", "GSE225740", "GSE135251")
    fibrosis_index <- c(42,45,45,41,44,37,43)
  }else{
    GSE <- c("GSE174478", "GSE193066", "GSE130970", "GSE192959", "GSE162694", "GSE225740", "GSE185051", "GSE135251")
    fibrosis_index <- c(42,45,45,41,44,37,44,43)
  }
  
  # Loop through each element in GSE
  for (i in 1:length(GSE)) {
    file_path <- paste(GSE[i], "/fibrosis_DESEQ2_",comb$B[c],"_VS_",comb$A[c],".csv", sep = "") # Construct the file path and read the CSV file
    studies[[i]] <- read.csv(file_path)  #get the study into list 
  }
  common_rows <- Reduce(intersect, lapply(studies, function(df) df$X)) #get common genes across each study
  # Filter each dataset to contain only common rows & sort them
  datasets_filtered <- lapply(studies, function(df) {
    df <- df[df$X %in% common_rows, ]  # Keep only common rows
    df <- df[order(df$X), ]  # Sort by column 'X'
    return(df)
  })
  
  library(ggplot2)
  library(patchwork)
  
  plot_list <- lapply(seq_along(datasets_filtered), function(i) {
    df <- datasets_filtered[[i]]
    study_name <- GSE[i]
    
    ggplot(df, aes(x = pvalue)) +
      geom_histogram(bins = 30, fill = "#1f78b4", color = "white") +
      theme_minimal(base_size = 12) +
      labs(
        title = study_name,
        x = "P-value",
        y = "Frequency"
      ) +
      theme(plot.title = element_text(hjust = 0.5))
  })
  
  # Combine all plots into a grid (automatically arranges)
  combined_plot <- wrap_plots(plot_list, ncol = 3)  # change ncol as needed
  
  # Save it
  ggsave(paste(c,"_combined_pval_histograms.png", sep=""), combined_plot, width = 12, height = 8, dpi = 600)
  
  # Create lists to store p-values, fold changes, and adjusted p-values
  rawpval <- lapply(1:length(datasets_filtered), function(i) datasets_filtered[[i]][["pvalue"]])
  FC <- lapply(1:length(datasets_filtered), function(i) datasets_filtered[[i]][["log2FoldChange"]])
  adjpval <- lapply(1:length(datasets_filtered), function(i) datasets_filtered[[i]][["padj"]])
  
  checked_for_p <- readxl::read_xlsx("ideal_p_value_distrubition.xlsx")
  
  
  studies <- GSE # List of study names
  datasets_filtered_by_distance <- list() #empty list
  studies_filtered_by_distance <- c() #empty vector
  index_filtered_by_distance <- c() #empty vector
  for (i in 1:length(datasets_filtered)){
    if (wasserstein1d(rawpval[[i]],checked_for_p$checked_for_p) <= 0.12){
      studies_filtered_by_distance <- c(studies_filtered_by_distance, studies[i])
      datasets_filtered_by_distance[[i]] <- datasets_filtered[[i]]
      index_filtered_by_distance <- c(index_filtered_by_distance, fibrosis_index[i])
    }
  }
  
  datasets_filtered_by_distance <- Filter(Negate(is.null), datasets_filtered_by_distance) #It removes NULL entries from the list datasets_filtered_by_distance.
```


```{r}
  ######### Parts below this are directly from metarnaseq tutorial (see second link at the begining of this file)
  
  
  #get the raw p-val logFC, and adj p val for filtered datasets
  rawpval_distance <- lapply(1:length(datasets_filtered_by_distance), function(i) datasets_filtered_by_distance[[i]][["pvalue"]])
  FC_distance <- lapply(1:length(datasets_filtered_by_distance), function(i) datasets_filtered_by_distance[[i]][["log2FoldChange"]])
  adjpval_distance <- lapply(1:length(datasets_filtered_by_distance), function(i) datasets_filtered_by_distance[[i]][["padj"]])
  
  # Apply DE calculation for each dataset
  DE <- mapply(function(x) ifelse(x <= 0.05, 1, 0), adjpval_distance) #Converting adjusted p-values into DE yes/no (binary)
  
  # Set column names for DE
  colnames(DE) <- paste("DE", studies_filtered_by_distance, sep=".") #label the columns with study names
  
  rep <- list() #Initializes an empty list to store sample counts (one per dataset).
  for (i in 1:length(studies_filtered_by_distance)){
    data <- load_dataset(studies_filtered_by_distance[i])
    meta <- load_meta(studies_filtered_by_distance[i])
    col_index <- index_filtered_by_distance[i]
    meta <- meta[rownames(meta) %in% colnames(data),] #only get the samples where count data is availasble
    print(colnames(meta)[col_index])
    colData <- as.data.frame(meta[,col_index]) # create the design df
    rownames(colData) <- rownames(meta) 
    print(sum(rownames(colData) != colnames(data))) # check whether rownames of colData is same with colnames of data !should return 0
    colnames(colData) <- "stage" #name NAS as score
    colData <- colData %>% mutate(
      stage = case_when(
        stage %in% c(0,1,"0","1") ~ "F0_F1",
        stage %in% c(2,"2") ~ "F2",
        stage %in% c(3,"3") ~ "F3",
        stage %in% c(4,"4") ~ "F4",
        TRUE ~ "NA"
      ))
    colData <- colData[!colData[, 1] == "NA", , drop = FALSE]
    data <- data[,colnames(data) %in% rownames(colData)]
    colData$stage <- as.factor(colData$stage) #factorize them
    sum(colData$stage %in% c(comb$A[c],comb$B[c])) #Counts how many samples in this dataset are from the two target groups
    rep <- append(rep,sum(colData$stage %in% c(comb$A[c],comb$B[c]))) #Appends the result to the rep list.
  }
  
  invnormcomb <- invnorm(rawpval_distance,nrep= as.vector(unlist(rep)), BHth = 0.05) 
  
  fishcomb <- fishercomb(rawpval_distance, BHth = 0.05)
  
  DEresults <- data.frame(DE,"DE.fishercomb"=ifelse(fishcomb$adjpval<=0.05,1,0),"DE.invnorm"=ifelse(invnormcomb$adjpval<=0.05,1,0))
  
  
  # Extract signs of fold changes
  signsFC <- mapply(FC_distance, FUN=function(x) sign(x))
  
  # Sum signs across studies to identify consistent/contradictory genes
  sumsigns <- apply(signsFC, 1, sum)
  commonsgnFC <- ifelse(abs(sumsigns) == dim(signsFC)[2], sign(sumsigns), 0)
  
  # Identify differentially expressed genes from meta-analysis
  unionDE <- unique(c(fishcomb$DEindices, invnormcomb$DEindices))
  
  # Create a table combining DE results, fold changes, and sign consistency
  FC.selecDE <- data.frame(DEresults[unionDE, ], 
                           do.call(cbind, FC_distance)[unionDE, ], 
                           signFC=commonsgnFC[unionDE])
  
  # Filter out conflicting genes (conflict of direction!)
  keepDE <- FC.selecDE[which(abs(FC.selecDE$signFC) == 1), ]
  conflictDE <- FC.selecDE[which(FC.selecDE$signFC == 0), ]
  
  # Check the number of conflicting genes
  cat("Total DE genes before filtering:", nrow(FC.selecDE), "\n")
  cat("DE genes after removing conflicts:", nrow(keepDE), "\n")
  cat("Conflicting genes removed:", nrow(conflictDE), "\n")
  
  # Save the cleaned results
  dim(keepDE)
  dim(conflictDE)
  
  ordered_gene_names <- common_rows[order(common_rows)]
  existing_genes_keep <- ordered_gene_names[as.numeric(rownames(keepDE))]
  rownames(keepDE) <- existing_genes_keep
  
  keepDE$average_logFC <- rowMeans(keepDE[,(length(studies_filtered_by_distance)+3):(2*length(studies_filtered_by_distance)+2)]) #calculate average logFC besides logFC for each study
  
  colnames(keepDE)[(length(studies_filtered_by_distance)+3):(2*length(studies_filtered_by_distance)+2)] <- paste0(studies_filtered_by_distance, "-FC") #rename logFC columns with their study names
  keepDE$Gene <- rownames(keepDE) #Moves the row names (gene IDs) into a proper Gene column.
  df <- keepDE[, c(ncol(keepDE), 1:(ncol(keepDE) - 1))] #Reorders columns so the new Gene column comes first in the dataframe.
  df <- df[df$DE.fishercomb == 1 & df$DE.invnorm == 1, ]
  write_xlsx(df, paste("Individual_Analysis_",as.character(comb$B[c]),"_VS_",as.character(comb$A[c]),".xlsx", sep = "")) #save
}
```

