---
title: "Sex_Stratified_ORA"
author: "Eren Kumak"
date: "2026-05-15"
output: html_document
---

```{r}
library(data.table)
library(org.Hs.eg.db)
library(GEOquery)
library(Rtsne)
library(ggfortify)
library(dplyr)
library(gridExtra)
library(sva)
library(limma)
library(DESeq2)
library(edgeR)
library(plotly)
library(rmarkdown)
library(vegan)
library(tidyr)
library(pheatmap)
library(rococo)
library(parallel)
library(pbapply)
library(kohonen)
library(writexl)
library(phenopath)
library(metaRNASeq)
set.seed(42)
```

## Fibrosis

```{r}

overview <- readxl::read_xlsx("overall_meta_analysis_overview_directions_fibrosis.xlsx")
cutoff <- quantile(overview$total, 0.95)
selected_genes <- overview[overview$total >= cutoff,]$Gene

male <- readxl::read_xlsx("fibrosis_male_Individual_Analysis_F4_VS_F0_F1.xlsx")
male <- male[male$DE.fishercomb == 1 & male$DE.invnorm == 1,]
male <- male[male$Gene %in% selected_genes,]

female <- readxl::read_xlsx("fibrosis_female_Individual_Analysis_F4_VS_F0_F1.xlsx")
female <- female[female$DE.fishercomb == 1 & female$DE.invnorm == 1,]
female <- female[female$Gene %in% selected_genes,]

genesets <- c("H","C1","C2","C3","C4","C5","C6","C7","C8")

for (i in genesets){
msig_hallmark <- msigdbr(species = "Homo sapiens", category = i)
hallmark_list <- msig_hallmark[, c("gs_name", "gene_symbol")]
ora_hallmark <- enricher(gene = male$Gene,
                         TERM2GENE = hallmark_list,
                         pAdjustMethod = "BH",
                         qvalueCutoff = 0.05)
data_framed_ora <- as.data.frame(ora_hallmark)
if (nrow(data_framed_ora) > 0){
write_xlsx(data_framed_ora, paste("gender/male_fibrosis_overview_msigdb_",i,".xlsx", sep=""))
p <- barplot(ora_hallmark,
             drop = TRUE,
             showCategory = 10,
             title = paste("MSigDB = ",i, " (Fibrosis)", sep = ""),
             font.size = 10)

# Save as 600 DPI PNG
ggsave(paste("gender/male_fibrosis_ORA_MSigDB_",i,".png", sep=""),
       plot = p,
       width = 8, height = 6, dpi = 600, units = "in")
}
}

#### same but only with upregulated


overview <- readxl::read_xlsx("overall_meta_analysis_overview_directions_fibrosis.xlsx")
cutoff <- quantile(overview$total, 0.95)
selected_genes <- overview[overview$total >= cutoff,]$Gene

male <- readxl::read_xlsx("fibrosis_male_Individual_Analysis_F4_VS_F0_F1.xlsx")
male <- male[male$DE.fishercomb == 1 & male$DE.invnorm == 1,]
male <- male[male$Gene %in% selected_genes,]
male <- male[male$signFC == 1,]

female <- readxl::read_xlsx("fibrosis_female_Individual_Analysis_F4_VS_F0_F1.xlsx")
female <- female[female$DE.fishercomb == 1 & female$DE.invnorm == 1,]
female <- female[female$Gene %in% selected_genes,]
female <- female[female$signFC == 1,]

genesets <- c("H","C1","C2","C3","C4","C5","C6","C7","C8")

for (i in genesets){
msig_hallmark <- msigdbr(species = "Homo sapiens", category = i)
hallmark_list <- msig_hallmark[, c("gs_name", "gene_symbol")]
ora_hallmark <- enricher(gene = female$Gene,
                         TERM2GENE = hallmark_list,
                         pAdjustMethod = "BH",
                         qvalueCutoff = 0.05)
data_framed_ora <- as.data.frame(ora_hallmark)
if (nrow(data_framed_ora) > 0){
write_xlsx(data_framed_ora, paste("gender/female_fibrosis_overview_msigdb_",i,"_upregulated.xlsx", sep=""))
p <- barplot(ora_hallmark,
             drop = TRUE,
             showCategory = 10,
             title = paste("MSigDB = ",i, " (Fibrosis)", sep = ""),
             font.size = 10)

# Save as 600 DPI PNG
ggsave(paste("gender/female_fibrosis_ORA_MSigDB_",i,"_upregulated.png", sep=""),
       plot = p,
       width = 8, height = 6, dpi = 600, units = "in")
}
}

#### same but only with downregulated


overview <- readxl::read_xlsx("overall_meta_analysis_overview_directions_fibrosis.xlsx")
cutoff <- quantile(overview$total, 0.95)
selected_genes <- overview[overview$total >= cutoff,]$Gene

male <- readxl::read_xlsx("fibrosis_male_Individual_Analysis_F4_VS_F0_F1.xlsx")
male <- male[male$DE.fishercomb == 1 & male$DE.invnorm == 1,]
male <- male[male$Gene %in% selected_genes,]
male <- male[male$signFC == -1,]

female <- readxl::read_xlsx("fibrosis_female_Individual_Analysis_F4_VS_F0_F1.xlsx")
female <- female[female$DE.fishercomb == 1 & female$DE.invnorm == 1,]
female <- female[female$Gene %in% selected_genes,]
female <- female[female$signFC == -1,]

genesets <- c("H","C1","C2","C3","C4","C5","C6","C7","C8")

for (i in genesets){
msig_hallmark <- msigdbr(species = "Homo sapiens", category = i)
hallmark_list <- msig_hallmark[, c("gs_name", "gene_symbol")]
ora_hallmark <- enricher(gene = male$Gene,
                         TERM2GENE = hallmark_list,
                         pAdjustMethod = "BH",
                         qvalueCutoff = 0.05)
data_framed_ora <- as.data.frame(ora_hallmark)
if (nrow(data_framed_ora) > 0){
write_xlsx(data_framed_ora, paste("gender/male_fibrosis_overview_msigdb_",i,"_downregulated.xlsx", sep=""))
p <- barplot(ora_hallmark,
             drop = TRUE,
             showCategory = 10,
             title = paste("MSigDB = ",i, " (Fibrosis)", sep = ""),
             font.size = 10)

# Save as 600 DPI PNG
ggsave(paste("gender/male_fibrosis_ORA_MSigDB_",i,"_downregulated.png", sep=""),
       plot = p,
       width = 8, height = 6, dpi = 600, units = "in")
}
}
```